//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//  Version 4.4.0.0 	www.ComponentFactory.com
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.CodeDom.Compiler;
using System.ComponentModel;
using System.Diagnostics;
using System.Diagnostics.CodeAnalysis;
using System.Drawing;
using System.Globalization;
using System.Resources;
using System.Runtime.CompilerServices;

namespace ComponentFactory.Krypton.Design.Properties {
	/// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [GeneratedCode("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [DebuggerNonUserCode()]
    [CompilerGenerated()]
    internal class Resources {
        
        private static ResourceManager resourceMan;
        
        private static CultureInfo resourceCulture;
        
        [SuppressMessage("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static ResourceManager ResourceManager {
            get {
                if (ReferenceEquals(resourceMan, null)) {
                    ResourceManager temp = new ResourceManager("ComponentFactory.Krypton.Design.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [EditorBrowsable(EditorBrowsableState.Advanced)]
        internal static CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static Bitmap add {
            get {
                object obj = ResourceManager.GetObject("add", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap arrow_down_blue {
            get {
                object obj = ResourceManager.GetObject("arrow_down_blue", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap arrow_up_blue {
            get {
                object obj = ResourceManager.GetObject("arrow_up_blue", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap delete2 {
            get {
                object obj = ResourceManager.GetObject("delete2", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap Empty16x16 {
            get {
                object obj = ResourceManager.GetObject("Empty16x16", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonBorderEdge {
            get {
                object obj = ResourceManager.GetObject("KryptonBorderEdge", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonBreadCrumb {
            get {
                object obj = ResourceManager.GetObject("KryptonBreadCrumb", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonBreadCrumbItem {
            get {
                object obj = ResourceManager.GetObject("KryptonBreadCrumbItem", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonButton {
            get {
                object obj = ResourceManager.GetObject("KryptonButton", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonButtonSpec {
            get {
                object obj = ResourceManager.GetObject("KryptonButtonSpec", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonCheckBox {
            get {
                object obj = ResourceManager.GetObject("KryptonCheckBox", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonCheckButton {
            get {
                object obj = ResourceManager.GetObject("KryptonCheckButton", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonCheckedListBox {
            get {
                object obj = ResourceManager.GetObject("KryptonCheckedListBox", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonCheckSet {
            get {
                object obj = ResourceManager.GetObject("KryptonCheckSet", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonColorButton {
            get {
                object obj = ResourceManager.GetObject("KryptonColorButton", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonComboBox {
            get {
                object obj = ResourceManager.GetObject("KryptonComboBox", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonCommand {
            get {
                object obj = ResourceManager.GetObject("KryptonCommand", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonContextMenu {
            get {
                object obj = ResourceManager.GetObject("KryptonContextMenu", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonContextMenuColorColumns {
            get {
                object obj = ResourceManager.GetObject("KryptonContextMenuColorColumns", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonContextMenuHeading {
            get {
                object obj = ResourceManager.GetObject("KryptonContextMenuHeading", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonContextMenuImageSelect {
            get {
                object obj = ResourceManager.GetObject("KryptonContextMenuImageSelect", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonContextMenuItem {
            get {
                object obj = ResourceManager.GetObject("KryptonContextMenuItem", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonContextMenuItems {
            get {
                object obj = ResourceManager.GetObject("KryptonContextMenuItems", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonContextMenuSeparator {
            get {
                object obj = ResourceManager.GetObject("KryptonContextMenuSeparator", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonDataGridView {
            get {
                object obj = ResourceManager.GetObject("KryptonDataGridView", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonDateTimePicker {
            get {
                object obj = ResourceManager.GetObject("KryptonDateTimePicker", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonDomainUpDown {
            get {
                object obj = ResourceManager.GetObject("KryptonDomainUpDown", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonDropButton {
            get {
                object obj = ResourceManager.GetObject("KryptonDropButton", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonForm {
            get {
                object obj = ResourceManager.GetObject("KryptonForm", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonGallery {
            get {
                object obj = ResourceManager.GetObject("KryptonGallery", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonGroup {
            get {
                object obj = ResourceManager.GetObject("KryptonGroup", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonGroupBox {
            get {
                object obj = ResourceManager.GetObject("KryptonGroupBox", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonGroupPanel {
            get {
                object obj = ResourceManager.GetObject("KryptonGroupPanel", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonHeader {
            get {
                object obj = ResourceManager.GetObject("KryptonHeader", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonHeaderGroup {
            get {
                object obj = ResourceManager.GetObject("KryptonHeaderGroup", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonLabel {
            get {
                object obj = ResourceManager.GetObject("KryptonLabel", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonLinkLabel {
            get {
                object obj = ResourceManager.GetObject("KryptonLinkLabel", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonListBox {
            get {
                object obj = ResourceManager.GetObject("KryptonListBox", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonManager {
            get {
                object obj = ResourceManager.GetObject("KryptonManager", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonMaskedTextBox {
            get {
                object obj = ResourceManager.GetObject("KryptonMaskedTextBox", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonMonthCalendar {
            get {
                object obj = ResourceManager.GetObject("KryptonMonthCalendar", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonNumericUpDown {
            get {
                object obj = ResourceManager.GetObject("KryptonNumericUpDown", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonPalette {
            get {
                object obj = ResourceManager.GetObject("KryptonPalette", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonPanel {
            get {
                object obj = ResourceManager.GetObject("KryptonPanel", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonRadioButton {
            get {
                object obj = ResourceManager.GetObject("KryptonRadioButton", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonRibbonContext {
            get {
                object obj = ResourceManager.GetObject("KryptonRibbonContext", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonRibbonGroup {
            get {
                object obj = ResourceManager.GetObject("KryptonRibbonGroup", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonRibbonGroupButton {
            get {
                object obj = ResourceManager.GetObject("KryptonRibbonGroupButton", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonRibbonGroupCheckBox {
            get {
                object obj = ResourceManager.GetObject("KryptonRibbonGroupCheckBox", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonRibbonGroupCluster {
            get {
                object obj = ResourceManager.GetObject("KryptonRibbonGroupCluster", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonRibbonGroupClusterButton {
            get {
                object obj = ResourceManager.GetObject("KryptonRibbonGroupClusterButton", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonRibbonGroupClusterColorButton {
            get {
                object obj = ResourceManager.GetObject("KryptonRibbonGroupClusterColorButton", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonRibbonGroupColorButton {
            get {
                object obj = ResourceManager.GetObject("KryptonRibbonGroupColorButton", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonRibbonGroupComboBox {
            get {
                object obj = ResourceManager.GetObject("KryptonRibbonGroupComboBox", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonRibbonGroupCustomControl {
            get {
                object obj = ResourceManager.GetObject("KryptonRibbonGroupCustomControl", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonRibbonGroupDateTimePicker {
            get {
                object obj = ResourceManager.GetObject("KryptonRibbonGroupDateTimePicker", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonRibbonGroupDomainUpDown {
            get {
                object obj = ResourceManager.GetObject("KryptonRibbonGroupDomainUpDown", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonRibbonGroupLabel {
            get {
                object obj = ResourceManager.GetObject("KryptonRibbonGroupLabel", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonRibbonGroupLines {
            get {
                object obj = ResourceManager.GetObject("KryptonRibbonGroupLines", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonRibbonGroupMaskedTextBox {
            get {
                object obj = ResourceManager.GetObject("KryptonRibbonGroupMaskedTextBox", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonRibbonGroupNumericUpDown {
            get {
                object obj = ResourceManager.GetObject("KryptonRibbonGroupNumericUpDown", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonRibbonGroupRadioButton {
            get {
                object obj = ResourceManager.GetObject("KryptonRibbonGroupRadioButton", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonRibbonGroupRichTextBox {
            get {
                object obj = ResourceManager.GetObject("KryptonRibbonGroupRichTextBox", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonRibbonGroupSeparator {
            get {
                object obj = ResourceManager.GetObject("KryptonRibbonGroupSeparator", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonRibbonGroupTextBox {
            get {
                object obj = ResourceManager.GetObject("KryptonRibbonGroupTextBox", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonRibbonGroupTrackBar {
            get {
                object obj = ResourceManager.GetObject("KryptonRibbonGroupTrackBar", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonRibbonGroupTriple {
            get {
                object obj = ResourceManager.GetObject("KryptonRibbonGroupTriple", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonRibbonQATButton {
            get {
                object obj = ResourceManager.GetObject("KryptonRibbonQATButton", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonRibbonRecentDoc {
            get {
                object obj = ResourceManager.GetObject("KryptonRibbonRecentDoc", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonRibbonTab {
            get {
                object obj = ResourceManager.GetObject("KryptonRibbonTab", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonRichTextBox {
            get {
                object obj = ResourceManager.GetObject("KryptonRichTextBox", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonSeparator {
            get {
                object obj = ResourceManager.GetObject("KryptonSeparator", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonSplitContainer {
            get {
                object obj = ResourceManager.GetObject("KryptonSplitContainer", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonTextBox {
            get {
                object obj = ResourceManager.GetObject("KryptonTextBox", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap KryptonWrapLabel {
            get {
                object obj = ResourceManager.GetObject("KryptonWrapLabel", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap MoveFirst {
            get {
                object obj = ResourceManager.GetObject("MoveFirst", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap MoveLast {
            get {
                object obj = ResourceManager.GetObject("MoveLast", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap MoveNext {
            get {
                object obj = ResourceManager.GetObject("MoveNext", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
        
        internal static Bitmap MovePrevious {
            get {
                object obj = ResourceManager.GetObject("MovePrevious", resourceCulture);
                return ((Bitmap)(obj));
            }
        }
    }
}
